In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('car.data')

In [4]:
df

     buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [6]:
df.nunique()

buying      4
maint       4
doors       4
persons     3
lug_boot    3
safety      3
class       4
dtype: int64

In [35]:
df['buying'].unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [37]:
df['safety'].unique()

array(['low', 'med', 'high'], dtype=object)

In [11]:
df['maint'].unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [79]:
df = df[['buying','safety', 'maint']]
df.head()

  buying safety  maint
0  vhigh    low  vhigh
1  vhigh    med  vhigh
2  vhigh   high  vhigh
3  vhigh    low  vhigh
4  vhigh    med  vhigh

In [125]:
x = df[['buying','safety']]
y = df['maint']    #double bracket lgata to ye 2d ban jata or sklearn nakhre karta isliye 1 [] se likha h to 1D hogya

In [131]:
from sklearn.model_selection import train_test_split

In [132]:
X_train ,X_test ,y_train ,y_test = train_test_split(x,y,test_size = 0.3,random_state = 1)
X_train.shape , y_train.shape

((1209, 2), (1209,))

In [133]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories =[['low','med','high','vhigh'],['low', 'med', 'high']])
oe.fit(X_train)

OrdinalEncoder(categories=[['low', 'med', 'high', 'vhigh'],
                           ['low', 'med', 'high']])

In [134]:
X_train = oe.transform(X_train)
X_train

array([[0., 0.],
       [2., 2.],
       [2., 2.],
       ...,
       [1., 1.],
       [3., 1.],
       [1., 2.]])

In [117]:
oe.categories_

[array(['low', 'med', 'high', 'vhigh'], dtype=object),
 array(['low', 'med', 'high'], dtype=object)]

In [108]:
X_train

array([[0., 0.],
       [2., 2.],
       [2., 2.],
       ...,
       [1., 1.],
       [3., 1.],
       [1., 2.]])

In [112]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [113]:
le.classes_

array(['high', 'low', 'med', 'vhigh'], dtype=object)

In [118]:
le.transform(y_train)

array([0, 1, 3, ..., 2, 2, 0])